version: "3.9"

services:

  db:

    image: postgres:16

    container_name: shipment_postgres

    restart: always

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: password

      POSTGRES_DB: shipment_db

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

  api:

    build: .

    container_name: shipment_api

    depends_on:

      - db

    ports:

      - "8000:8000"

    env_file:
      - .env

    environment:

      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/shipment_db

volumes:

  postgres_data: